site_name: TensorFlow Builder’s Companion Book
site_url: https://github.com/McKlay/tf-companion-book/
site_author: Clay Mark Sarte
site_description: A personal TensorFlow companion book by Clay Mark Sarte — deep dives into the TensorFlow API for learners, devs, and researchers.

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  hide:
    - toc

nav:
  - Table of Contents: index.md

  - "":
      - "&nbsp; Preface": Preface.md
      - "&nbsp;&nbsp; 📖 Part I: Foundations": PartI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 1": chapter1_what_is_tensorflow.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 2": chapter2_TF_architecture.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 3": chapter3_tensorflow_vs_keras.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 4": chapter4_installation_and_setup.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 5": chapter5_Hello_tf_tensor.md

      - "&nbsp;&nbsp; 📖 Part II: Tensor Mechanics": PartII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 6": chapter6_tensor_indexing_reshaping.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 7": chapter7_tensor_broadcasting.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 8": chapter8_ragged_sparse_string.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 9": chapter9_variable_trainable_param.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 10": chapter10_automatic_differentiation.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 11": chapter11_graphs_functions.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 12": chapter12_bitwise_numerical_ops.md

      - "&nbsp;&nbsp; 📖 Part III: Special Modules": PartIII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 13": chapter13_API.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 14": chapter14_nn_from_scratch.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 15": chapter15_layers.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 16": chapter16_loss_optim.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 17": chapter17_backprop.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 18": chapter18_training.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 19": chapter19_saving_loading.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 20": chapter20_visualizing.md

      - "&nbsp;&nbsp; 📖 Part IV: NLP": PartIV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 21": chapter21_text_tokenization.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 22": chapter22_TF_IDF.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 23": chapter23_RNN_LSTM.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 24": chapter24_transformers.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 25": chapter25_projects.md

      - "&nbsp;&nbsp; 📖 Part V: Computer Vision": PartV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 26": chapter26_cnn.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 27": chapter27_data_augmentation.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 28": chapter28_img_class.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 29": chapter29_obj_detection.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 30": chapter30_face_mask_dete.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 31": chapter31_image_segmentation.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 32": chapter32_GANs.md

      - "&nbsp;&nbsp; 📖 Part VI: Real-World App": PartVI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 28": chapter33_time_series.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 29": chapter34_recom_systems.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 30": chapter35_TF_Lite.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 31": chapter36_TFX.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 32": chapter37_TF_HuggingFace.md

      - "&nbsp;&nbsp; 📖 Appendices": appendices.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McKlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/clay-mark-sarte-283855147/
